version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project-management
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  app:
    build:
      context: ./Project-Management
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      JWT_SECRET: "secret"
      EXPIRY_TIME: "3600"
    volumes:
      - ./prisma:/app/prisma

  init-sysadmin:
    build:
      context: .
      dockerfile: Dockerfile.init
    depends_on:
      - db
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      SYSADMIN_EMAIL: "${SYSADMIN_EMAIL}"
      SYSADMIN_PASSWORD: "${SYSADMIN_PASSWORD}"
    volumes:
      - ./prisma:/app/prisma

  mqtt:
    build:
      context: ./Broker-mqtt
      dockerfile: Dockerfile
    ports:
      - 1883:1883
    depends_on:
      - db
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      MQTT_HOST: "${MQTT_HOST}"
      MQTT_CLIENT_ID: "${MQTT_CLIENT_ID}"
      MQTT_USERNAME: "${MQTT_USERNAME}"
      MQTT_PASSWORD: "${MQTT_PASSWORD}"
    volumes:
      - ./prisma:/app/prisma

volumes:
  postgres_data:
