name: "BUILD DOCKER IMAGE"
description: "BUILD DOCKER IMAGE"
inputs:
  file:
    required: false
    description: "The dockerfile path"
    default: ./Dockerfile
  context:
    required: false
    description: "The context of build"
    default: .
  tags:
    required: true
    description: "The tags of image"
  push:
    required: true
    description: "Push image"
  dockerhub-username:
    required: false
    description: "dockerhub username"
  dockerhub-token:
    required: false
    description: "dockerhub token"
  login:
    required: true
    description: "to Login or not"

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Context for Buildx
      id: buildx-context
      shell: bash
      run: |
        docker context create builders

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
        endpoint: builders

    - name: Verify Buildx installation
      shell: bash
      run: docker buildx ls

    - name: Login to DockerHub
      if: ${{ inputs.login == 'true' }}
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}

    - name: Build and push image to DockerHub
      uses: docker/build-push-action@v2
      with:
        push: ${{ inputs.push }}
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        tags: ${{ inputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
